version: '3'

services:
  # Сервис PostgresSQL
  postgres:
    container_name: "postgres"
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - custom


  #Сервис FastAPI
  fastapi_example:
    build:
      context: .
      dockerfile: Dockerfile
    image: ekb-example-image-name:latest
    container_name: "fastapi_example"
    restart: unless-stopped
#    command: bash -c "alembic upgrade heads && app.main:app --host 0.0.0.0 --port 8000 --reload"
    command: [ "/app_example/docker/app.sh" ]
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - custom


volumes:
  postgres_storage:

networks:
  custom: