"""init

Revision ID: ce99ba7db68f
Revises: 
Create Date: 2024-02-09 20:59:09.665733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce99ba7db68f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_tasks',
    sa.Column('status_closed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('task_shift', sa.String(length=100), nullable=False),
    sa.Column('line', sa.String(length=100), nullable=False),
    sa.Column('shift', sa.String(length=100), nullable=False),
    sa.Column('brigade', sa.String(length=100), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('batch_date', sa.Date(), nullable=False),
    sa.Column('nomenclature', sa.String(length=255), nullable=False),
    sa.Column('ecn_code', sa.String(length=6), nullable=False),
    sa.Column('rc_identifier', sa.String(length=10), nullable=False),
    sa.Column('date_started_shift', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_end_shift', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_tasks')
    # ### end Alembic commands ###
