name: Push_docker_images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
        poetry-version: [1.7.1]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install dependencies poetry
      run: poetry install
    - name: Run poetry black
      run:
        poetry run black . --check
    - name: Run poetry flake8
      run: poetry run flake8 .
    - name: Run isort
      run: poetry run isort . --check-only --profile black

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1


  postgres_and_tests:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: [ 3.11 ]
        poetry-version: [ 1.7.1 ]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies poetry
        run: poetry install

      - name: Set up environment variables
        run: |
          echo "MODE=DEV" >> $GITHUB_ENV
          echo "DATABASE_USER=postgres" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=postgres" >> $GITHUB_ENV
          echo "DATABASE_HOST=localhost" >> $GITHUB_ENV
          echo "DATABASE_PORT=5432" >> $GITHUB_ENV
          echo "DATABASE_NAME=example_ekb" >> $GITHUB_ENV
          echo "TEST_DATABASE_USER=postgres" >> $GITHUB_ENV
          echo "TEST_DATABASE_PASSWORD=postgres" >> $GITHUB_ENV
          echo "TEST_DATABASE_HOST=localhost" >> $GITHUB_ENV
          echo "TEST_DATABASE_PORT=5432" >> $GITHUB_ENV
          echo "TEST_DATABASE_NAME=postgres" >> $GITHUB_ENV

      - name: Run poetry pytest
        run:
          poetry run pytest



  build_and_push_docker_image:
    runs-on: ubuntu-latest
    needs: postgres_and_tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "nikerofeev/example_ekb:latest"
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
